

title: sounds about riso .online
email: your-email@example.com
description: ONLINE GALLERY, MARKET, & EVENT SPACE
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.soundsaboutriso.online" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: 
plugins:
  - jekyll-feed
  - jekyll-srcset

kramdown:
  parse_block_html: true
permalink: pretty
collections:
  works:
    output: true
  interviews:
    output: true

# defaults:
#   -
#     scope:
#       path: ""
#       type: "paintings"
#     values:
#       layout: "painting"